name: Cypress Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1,3,5'

jobs:
  login-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, electron ]
    name: Cypress tests using ${{ matrix.browser }} browser
    container:
      image: cypress/browsers:node16.16.0-chrome105-ff104-edge
      options: --user 1001  # THIS IS THE IMPORTANT LINE TO ENABLE DIRECTORY CREATION!
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm dependencies using Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: npm install

      - name: Test run
        run: npx cypress run --browser=${{ matrix.browser }} --env grepTags="-@smoke" --record --key ${{secrets.CYPRESS_RECORD_KEY}} --reporter mochawesome --reporter-options reportDir=mochawesome-report,overwrite=false KEY=${{secrets.CIPHER_KEY}}

      - name: List report files
        run: |
          echo "Listing mochawesome-report directory contents:"
          ls -al mochawesome-report
          echo "Displaying mochawesome.json contents:"
          cat mochawesome-report/mochawesome.json

      - name: Generate report
        run: npx mochawesome-merge 'mochawesome-report/*.json' > mochawesome.json && npx marge mochawesome.json -f index -o public

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-report-${{ matrix.browser }}
          path: public

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos